### ISSUE TITLE
Button Color

### ISSUE THREAD

**Issue by wslack** [tagawa/newsforbetty#10]
The Capital City Charter School would like to suggest that the buttons can be green or purple.

**Comment by tagawa** [comment]
Thanks for the comment @wslack  - I'll see what Betty thinks.
Is there a usability reason (or research data) for suggesting green or purple, or is it just preference?

**Comment by wslack** [comment]
I was telling a group of high school students visiting 18F about News for Betty and how anyone could suggest something, and they asked to post this! No research data, I think this can be a safely low priority.

**Comment by tagawa** [comment]
Aha, got it! I'm not a designer so I appreciate their creative input and made a test page here:
https://tagawa.github.io/newsforbetty-dev/
However Betty should get the final say so we'll see what she thinks.

**Comment by tagawa** [comment]
Hi @wslack. Thought you'd like to know I added some category buttons today in... green! Please thank the students for their suggestion if you see them again.

**Comment by wslack** [comment]
How can they be seen? I don't see the colors. Will def send to students.

**Comment by tagawa** [comment]
If you click on "New York Times" or "Washington Post" they should appear below.

**Comment by wslack** [comment]
got it, thanks!

-Will

On Sat, Apr 11, 2015 at 3:06 AM, Daniel Davis notifications@github.com
wrote:

> If you click on "New York Times" or "Washington Post" they should appear
> below.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/tagawa/newsforbetty/issues/10#issuecomment-91781353.

## 

_Will Slack_
Business Strategy

*18F  https://18f.gsa.gov/|OCSIT
http://www.gsa.gov/portal/category/25729 *

_|_

_GSA http://www.gsa.gov/portal/category/100000_
_william.slack@gsa.gov william.slack@gsa.gov_
