### ISSUE TITLE
New RSS Feeds - what's needed for the URL?

### ISSUE THREAD

**Issue by wslack** [tagawa/newsforbetty#9]
If you can post instructions for getting the proper RSS address for other sites, I can add a few from the CS Monitor or CNN. Do we need the Yahoo API?

**Comment by tagawa** [comment]
Thanks for the offer. I've just put [instructions in the README file](https://github.com/tagawa/newsforbetty/blob/gh-pages/README.md) but just creating an issue with the website address is fine.
